# -*- coding: utf-8 -*-
"""Granite_3_3_2B_Demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13fjr_lKK2YzQC7Kq9pIV-YnpX2qEKQe1
"""

!pip install -U transformers

from transformers import pipeline

pipe = pipeline(
    "text-generation",
    model="ibm-granite/granite-3.3-2b-instruct"
)

messages = [
    {"role": "user", "content": "Who are you?"}
]

response = pipe(messages)

print(response)

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

tokenizer = AutoTokenizer.from_pretrained(
    "ibm-granite/granite-3.3-2b-instruct"
)

model = AutoModelForCausalLM.from_pretrained(
    "ibm-granite/granite-3.3-2b-instruct",
    device_map="auto"
)

messages = [
    {"role": "user", "content": "Who are you?"}
]

inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt=True,
    return_dict=True,
    return_tensors="pt"
).to(model.device)

outputs = model.generate(
    **inputs,
    max_new_tokens=40
)

response = tokenizer.decode(
    outputs[0][inputs["input_ids"].shape[-1]:],
    skip_special_tokens=True
)

print(response)

!pip install -q transformers gradio json5 jsonschema python-dotenv pydantic

import gradio as gr
import json
import re
from datetime import datetime
from enum import Enum
from typing import Dict, List, Any, Tuple
from collections import deque
from jsonschema import validate, ValidationError

# ============================================================
# JSON REFINER CORE ENGINE
# ============================================================

class CaseStyle(Enum):
    SNAKE_CASE = "snake_case"
    CAMEL_CASE = "camelCase"
    KEBAB_CASE = "kebab-case"
    PASCAL_CASE = "PascalCase"


class JSONRefinerCore:

    # ------------------------------
    # CASE CONVERSION
    # ------------------------------

    @staticmethod
    def to_snake_case(text: str) -> str:
        text = re.sub(r'[\s\-]+', '_', text)
        text = re.sub(r'([a-z])([A-Z])', r'\1_\2', text)
        text = re.sub(r'[^a-zA-Z0-9_]', '', text)
        return text.lower()

    @staticmethod
    def to_camel_case(text: str) -> str:
        snake = JSONRefinerCore.to_snake_case(text)
        parts = snake.split('_')
        return parts[0] + ''.join(word.capitalize() for word in parts[1:])

    @staticmethod
    def to_kebab_case(text: str) -> str:
        snake = JSONRefinerCore.to_snake_case(text)
        return snake.replace("_", "-")

    @staticmethod
    def to_pascal_case(text: str) -> str:
        camel = JSONRefinerCore.to_camel_case(text)
        return camel[0].upper() + camel[1:] if camel else ""

    @staticmethod
    def normalize_key(key: str, case_style: CaseStyle):
        key = key.strip()

        if case_style == CaseStyle.SNAKE_CASE:
            return JSONRefinerCore.to_snake_case(key)

        if case_style == CaseStyle.CAMEL_CASE:
            return JSONRefinerCore.to_camel_case(key)

        if case_style == CaseStyle.KEBAB_CASE:
            return JSONRefinerCore.to_kebab_case(key)

        if case_style == CaseStyle.PASCAL_CASE:
            return JSONRefinerCore.to_pascal_case(key)

        return key

    # ------------------------------
    # TYPE INFERENCE
    # ------------------------------

    @staticmethod
    def infer_type(value: str):

        value = value.strip()

        if value.lower() in ["null", "none", "nil", "undefined"]:
            return None

        if value.lower() in ["true", "yes", "on"]:
            return True

        if value.lower() in ["false", "no", "off"]:
            return False

        try:
            if "." not in value:
                return int(value)
        except:
            pass

        try:
            return float(value)
        except:
            pass

        if value.startswith("[") and value.endswith("]"):
            try:
                return json.loads(value)
            except:
                pass

        if value.startswith("{") and value.endswith("}"):
            try:
                return json.loads(value)
            except:
                pass

        return value

    # ------------------------------
    # KEY VALUE PARSER
    # ------------------------------

    @staticmethod
    def parse_key_value_text(text: str, case_style: CaseStyle):

        result = {}
        errors = []

        lines = text.split("\n")

        for i, line in enumerate(lines, 1):

            line = line.strip()

            if not line or line.startswith("#"):
                continue

            if ":" not in line:
                errors.append(f"Line {i}: Missing ':' separator")
                continue

            key, value = line.split(":", 1)

            key = key.strip()
            value = value.strip()

            if not key:
                errors.append(f"Line {i}: Empty key")
                continue

            normalized = JSONRefinerCore.normalize_key(key, case_style)

            converted_value = JSONRefinerCore.infer_type(value)

            if normalized in result:
                errors.append(f"Duplicate key '{normalized}' overwritten")

            result[normalized] = converted_value

        return result, errors

    # ------------------------------
    # JSON FLATTEN
    # ------------------------------

    @staticmethod
    def flatten_json(data: Dict, parent_key="", sep="."):

        items = []

        for k, v in data.items():

            new_key = f"{parent_key}{sep}{k}" if parent_key else k

            if isinstance(v, dict):
                items.extend(
                    JSONRefinerCore.flatten_json(v, new_key, sep).items()
                )

            elif isinstance(v, list):

                for i, item in enumerate(v):

                    if isinstance(item, dict):
                        items.extend(
                            JSONRefinerCore.flatten_json(
                                item, f"{new_key}.{i}", sep
                            ).items()
                        )
                    else:
                        items.append((f"{new_key}.{i}", item))

            else:
                items.append((new_key, v))

        return dict(items)

    # ------------------------------
    # UNFLATTEN
    # ------------------------------

    @staticmethod
    def unflatten_json(data: Dict, sep="."):

        result = {}

        for key, value in data.items():

            parts = key.split(sep)

            current = result

            for part in parts[:-1]:

                if part not in current:
                    current[part] = {}

                current = current[part]

            current[parts[-1]] = value

        return result

    # ------------------------------
    # MERGE JSON
    # ------------------------------

    @staticmethod
    def merge_json_objects(*objects):

        result = {}

        for obj in objects:

            for k, v in obj.items():

                if (
                    k in result
                    and isinstance(result[k], dict)
                    and isinstance(v, dict)
                ):
                    result[k] = JSONRefinerCore.merge_json_objects(result[k], v)

                else:
                    result[k] = v

        return result

    # ------------------------------
    # REMOVE NULLS
    # ------------------------------

    @staticmethod
    def remove_null_values(data: Dict):

        result = {}

        for k, v in data.items():

            if v is None:
                continue

            if isinstance(v, dict):
                result[k] = JSONRefinerCore.remove_null_values(v)
            else:
                result[k] = v

        return result

    # ------------------------------
    # JSON STATS
    # ------------------------------

    @staticmethod
    def get_json_stats(data: Dict):

        def count(obj):

            if isinstance(obj, dict):
                total = len(obj)
                nested = 0

                for v in obj.values():
                    c, n = count(v)
                    nested += c + n

                return total, nested

            if isinstance(obj, list):
                total = len(obj)
                nested = 0

                for item in obj:
                    c, n = count(item)
                    nested += c + n

                return total, nested

            return 0, 0

        top, nested = count(data)

        return {
            "top_level_keys": top,
            "total_keys": top + nested,
            "has_nested": any(isinstance(v, dict) for v in data.values()),
            "has_arrays": any(isinstance(v, list) for v in data.values()),
            "value_types": list(set(type(v).__name__ for v in data.values())),
        }


# ============================================================
# GLOBALS
# ============================================================

refiner = JSONRefinerCore()

history = deque(maxlen=100)


# ============================================================
# MAIN FUNCTIONS
# ============================================================

def refine_json(text, case_style, remove_nulls, flatten, pretty):

    if not text.strip():
        return "", "❌ Empty input", ""

    case_enum = CaseStyle(case_style)

    data, errors = refiner.parse_key_value_text(text, case_enum)

    if remove_nulls:
        data = refiner.remove_null_values(data)

    if flatten:
        data = refiner.flatten_json(data)

    if pretty:
        output = json.dumps(data, indent=2)
    else:
        output = json.dumps(data)

    stats = refiner.get_json_stats(data)

    stats_text = f"""
Top Level Keys: {stats['top_level_keys']}
Total Keys: {stats['total_keys']}
Has Nested: {stats['has_nested']}
Has Arrays: {stats['has_arrays']}
Types: {', '.join(stats['value_types'])}
"""

    history.append(
        {
            "time": datetime.now().isoformat(),
            "input": text,
            "output": output,
        }
    )

    status = "✅ JSON generated"

    if errors:
        status += "\nWarnings:\n" + "\n".join(errors)

    return output, status, stats_text


def validate_json(json_text, schema_text, required):

    try:

        data = json.loads(json_text)

        messages = []

        if required.strip():

            fields = [f.strip() for f in required.split(",")]

            missing = [f for f in fields if f not in data]

            if missing:
                messages.append("Missing: " + ", ".join(missing))
            else:
                messages.append("Required fields OK")

        if schema_text.strip():

            schema = json.loads(schema_text)

            try:
                validate(data, schema)
                messages.append("Schema valid")

            except ValidationError as e:
                messages.append(str(e))

        if not messages:
            messages.append("Valid JSON")

        return "\n".join(messages), "Validation done"

    except Exception as e:
        return str(e), "Validation error"


def convert_case(json_text, target):

    try:

        data = json.loads(json_text)

        case_enum = CaseStyle(target)

        def convert(obj):

            if isinstance(obj, dict):
                return {
                    refiner.normalize_key(k, case_enum): convert(v)
                    for k, v in obj.items()
                }

            if isinstance(obj, list):
                return [convert(i) for i in obj]

            return obj

        result = convert(data)

        return json.dumps(result, indent=2), "Converted"

    except Exception as e:
        return "", str(e)


# ============================================================
# UI
# ============================================================

with gr.Blocks(title="JSON Refiner Advanced") as demo:

    gr.Markdown("# 🚀 JSON Refiner Advanced")

    with gr.Tab("Refine"):

        text_input = gr.Textbox(
            label="Key Value Input",
            lines=10,
            value="name: John\nage: 30\nactive: true",
        )

        case_style = gr.Radio(
            ["snake_case", "camelCase", "kebab-case", "PascalCase"],
            value="snake_case",
        )

        remove_nulls = gr.Checkbox(label="Remove Nulls")

        flatten = gr.Checkbox(label="Flatten")

        pretty = gr.Checkbox(label="Pretty Print", value=True)

        btn = gr.Button("Refine JSON")

        output = gr.Code(language="json")

        status = gr.Markdown()

        stats = gr.Markdown()

        btn.click(
            refine_json,
            [text_input, case_style, remove_nulls, flatten, pretty],
            [output, status, stats],
        )

    with gr.Tab("Validate"):

        json_input = gr.Code(language="json")

        schema = gr.Code(language="json")

        required = gr.Textbox(label="Required fields")

        btn2 = gr.Button("Validate")

        result = gr.Markdown()

        status2 = gr.Markdown()

        btn2.click(
            validate_json,
            [json_input, schema, required],
            [result, status2],
        )

    with gr.Tab("Case Conversion"):

        json_case = gr.Code(language="json")

        target_case = gr.Radio(
            ["snake_case", "camelCase", "kebab-case", "PascalCase"]
        )

        btn3 = gr.Button("Convert")

        case_output = gr.Code(language="json")

        case_status = gr.Markdown()

        btn3.click(
            convert_case,
            [json_case, target_case],
            [case_output, case_status],
        )


demo.launch()